apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: django-replicaset
spec:
  replicas: 3     #how many pods we need
  selector:
    matchLabels:
      app: django  #pods relevant to the replicaset
  template:        #blueprint to create a pod
    metadata:
      labels:
        app: django 
        # Ensures newly created Pods have this label
    spec:
      containers:
      - name: django-container
        image: duvindune/repo11:v1.0
        ports:
        - containerPort: 8000  # if you plan to access the container 
          # via a Service, you should specify it so the Service knows 
          # the target port.


# kubectl get pods -l app=myapp