# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: dj-app
# data:
#   SECRET_KEY: "django-insecure--@u)%e+8o@tfhle%^np*ydyh&-1ybd3gpsl=ko)nu07w=v6n*&"


---
apiVersion: v1
kind: Secret
metadata:
  name: dj-app
type: Opaque
stringData:
  SECRET_KEY: "django-insecure--@u)%e+8o@tfhle%^np*ydyh&-1ybd3gpsl=ko)nu07w=v6n*&"