apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
  annotations:
    "kubernetes.io/change-cause": "initial state"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: duvindune/repo7:v1.0
        ports:
          - containerPort: 8000

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "192Mi"
            cpu: "750m"
        
        startupProbe:
          httpGet:
            path: /health/startup/
            port: 8000
          failureThreshold: 10
          periodSeconds: 5
        
        readinessProbe:
          httpGet:
            path: /health/ready/
            port: 8000
          failureThreshold: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health/live/
            port: 8000
          failureThreshold: 10
          periodSeconds: 5