apiVersion: v1
kind: Pod
metadata:
  name: django-pod2
  namespace: dev
  labels:
    app: django  # match with service template, rs, dep
  annotations:
    description: "django pod for learning"
spec:
  containers: 
  - image: duvindune/repo1:v1
    name: django-container
    ports:
    - containerPort: 8000





