apiVersion: v1
kind: Service
metadata:
  name: nginx-service        # Service name
spec:
  type: ClusterIP            # Internal service (default type)
  selector:
    app: nginx               # Must match pod label
  ports:
    - protocol: TCP
      port: 80               # Service port
      targetPort: 80         # Container port