apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    app: django  # match with service template, rs, dep
  annotations:
    description: "django pod for learning"
spec:
  containers: 
  - image: duvindune/repo11:v1.0
    name: django-container
    ports:
    - containerPort: 8000

--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
  annotations:
    description: "nginx pod for learning"
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80





